name: Build and deploy ASP.Net Core app to Azure Web App - PerfectHome

on:
  push:
    branches:
      - master-deployment-backend
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build szgd.server --configuration Release

      - name: Publish .NET application
        run: dotnet publish szgd.server -c Release -o ./publish  # Zmieniona ścieżka na ./publish

      - name: List files in publish folder (Debugging)
        run: dir ./publish  # Dodany krok debugowania

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish  # Zmieniona ścieżka na ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: List files in downloaded folder (Debugging)
        run: dir ./  # Sprawdzenie zawartości folderu po pobraniu artefaktu

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'PerfectHome'
          slot-name: 'Production'
          package: ./publish  # Zmieniona ścieżka na ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5AF9D397777B45BFA3D32689C430B62B }}
